### ISSUE TITLE
Determine what ``BlocklistHandler`` is about.

### ISSUE THREAD

**Issue by MiniOranges** [MiniOranges/starwatch#56]
Seems to be referencing someone in specific. If so, needs to be rewritten to be more general purpose instead of one-case use.
https://github.com/MiniOranges/starwatch/blob/7a572955844bdbce61c71f85606585f5f5f232d2/Starwatch.Core/API/Web/BlocklistHandler.cs#L35

**Comment by Lachee** [comment]
https://community.postman.com/t/403modsecurity-action/7159/2
Original reference seem to have been taken down. 

TL;DR that is just what 403 Forbidden means.

**Comment by MiniOranges** [comment]
Ahh lol
